---
env: "testnet"
qredochain_version: "1.10.6"
qredochain_file_shor_sha: "cb4a29101"
qredochain_file_sufix: "tar.gz"
qredochain_sig_file_sifux: "sig"
qredochain_release_url: "https://github.com/qredo/qredochain-validators/releases/download/v{{ qredochain_version }}/{{ service_name }}.{{ qredochain_version }}-{{ qredochain_file_shor_sha }}.{{qredochain_file_sufix }}"
qredochain_snapshot_url: "https://snapshots.{{ env }}.qredo.network/"
qredochain_snapshot_auth: "am9objpmb29iYXI="
qredochain_sentry_endpoint: "sentries.{{ env }}.qredo.network"
qredochain_peer_1_port: "26657"
qredochain_peer_1_id: "a7ddd8f930ac6052c91ac5c644c5c5a688c0998e"
qredochain_peer_2_port: "36657"
qredochain_peer_2_id: "aba0cee06cb353b55d1e358c9236dc736c7d1f9c"
