---
- name: Create service user
  ansible.builtin.user:
    name: "{{ service_name }}"
    shell: /bin/bash
    home: "{{ service_dir }}"
    state: present
  changed_when: true

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ service_name }}"
    group: "{{ service_name }}"
    mode: 0770
  loop:
    - "{{ service_dir }}/bin"
    - "{{ service_dir }}/assets"

- name: Upload Qredo pub key
  ansible.builtin.copy:
    src: "./{{ item }}"
    dest: "{{ service_dir }}/assets"
    owner: "{{ service_name }}"
    group: "{{ service_name }}"
    mode: 0755
  loop:
    - "qredo.pub.pem"
