---
- block:
    - name: Check Operating System
      debug:
        msg: "Operating System not supported: {{ ansible_distribution }}-{{ ansible_distribution_major_version }}"
    - ansible.builtin.meta: end_host
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version != "20" and ansible_distribution_major_version != "22") or
        (ansible_distribution == "Amazon" and ansible_distribution_major_version != "2023")

- name: Install dependencies
  ansible.builtin.include_tasks: setup_Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Install dependencies
  ansible.builtin.include_tasks: setup_Amazon.yml
  when: ansible_distribution == 'Amazon'

- name: Configure service username and home directory
  ansible.builtin.include_tasks: init_user.yml

- name: Download and verify qredochain binary
  ansible.builtin.include_tasks: download_qredochain.yml

- name: Download latest snapshot and init qredochain directoty
  ansible.builtin.include_tasks: init_qredochain.yml

- name: Configure systemd service
  ansible.builtin.include_tasks: systemd.yml

- name: Install qrdo binary
  ansible.builtin.include_tasks: qrdo.yml
