---
env: "mainnet"
qredochain_version: "1.10.6"
qredochain_file_shor_sha: "cb4a29101"
qredochain_file_sufix: "tar.gz"
qredochain_sig_file_sifux: "sig"
qredochain_release_url: "https://github.com/qredo/qredochain-validators/releases/download/v{{ qredochain_version }}/{{ service_name }}.{{ qredochain_version }}-{{ qredochain_file_shor_sha }}.{{qredochain_file_sufix }}"
qredochain_snapshot_url: "https://snapshots.{{ env }}.qredo.network/"
qredochain_snapshot_auth: "VHJlbW9yNTQ4NDpKS1hUSm45QSNrVWhGJSUyVjZAQzl4dWpmOFElQ3NlUw=="
qredochain_sentry_endpoint: "sentries.{{ env }}.qredo.network"
qredochain_peer_1_port: "26656"
qredochain_peer_1_id: "344f5ff05193621d85eb23cee659bd11244328d1"
qredochain_peer_2_port: "36656"
qredochain_peer_2_id: "444f5ff05193621d85eb23cee659bd11244328d1"
